### ISSUE TITLE
vultr_firewall_rule expects protocol number

### ISSUE THREAD

**Issue by scross01** [vultr/terraform-provider-vultr-community#84]
Using terrform-provider-vultr built from latest main branch and Terraform 0.12

```
$ terraform --version
Terraform v0.12.3
+ provider.vultr (unversioned)
```

The `vultr_firewall_rule` example [here](https://github.com/vultr/terraform-provider-vultr/blob/master/docs/r/firewall_rule.html.markdown) shows the protocol is set with a name

```
resource "vultr_firewall_rule" "my_firewallrule" {
    firewall_group_id = "${vultr_firewall_group.my_firewallgroup.id}"
    protocol = "TCP"
    network = "0.0.0.0/0"
    from_port = "8085"
    to_port = "8090"
}
```

But applying a config with a `vultr_firewall_rule` returns an error that the protocol should be a number. e.g

```
vultr_firewall_rule.ssh: Creating...

Error: Err creating firewall group : Unable to add rule: Invalid protocol (must be one of 1, 6, 17, 47, 50)

  on firewall.tf line 10, in resource "vultr_firewall_rule" "ssh":
  10: resource vultr_firewall_rule ssh {

```

Changing the `protocol` to a number (e.g. 6 for TCP) doesn't work as the apply is passing the number as a string with Terraform 0.12

```
Terraform will perform the following actions:

  # vultr_firewall_rule.ssh will be created
  + resource "vultr_firewall_rule" "ssh" {
      + firewall_group_id = "70d64090"
      + from_port         = 22
      + id                = (known after apply)
      + ip_type           = (known after apply)
      + network           = "0.0.0.0/0"
      + protocol          = "6"
      + to_port           = 22
    }
```

**Comment by ddymko** [comment]
@scross01 

Thanks for creating the ticket!

So the problem here is our doc example is showing it as "TCP" all upper case however the Vultr API requires them to be all lowercase. If you change "TCP" to "tcp" this will work. 

As for the error

`Error: Err creating firewall group : Unable to add rule: Invalid protocol (must be one of 1, 6, 17, 47, 50)`

This error is returned from the Vultr API and is a bit deceiving since the api **requires** a string of "tcp udp etc" and the API does a translation of that to an int value. 

So for now if you use all lower case values for your firewall_rule (icmp, tcp, udp, gre). This will solve your issue. 

We will look into making the protocol case insensitive to prevent any headaches like this down the road. We will also update the docs on this repo.

Also we are working on improving our Vultr APIs to provide more clear error responses.

The API call and possible values:
https://www.vultr.com/api/#firewall_rule_create

Hopefully this helps resolve your issue for now while we working on fixing the case-sensitivity issue

**Comment by scross01** [comment]
@ddymko changing "TCP" to "tcp" gets past that error, but now I get an invalid port error:

```
vultr_firewall_rule.ssh: Creating...

Error: Err creating firewall group : Unable to add rule: Invalid port number - must be between 1 and 65535

  on firewall.tf line 11, in resource "vultr_firewall_rule" "ssh":
  11: resource vultr_firewall_rule ssh {
```

config is:

```hcl
resource vultr_firewall_rule ssh {
    firewall_group_id = vultr_firewall_group.default.id
    protocol = "tcp"
    network = "0.0.0.0/0"
    from_port = 22
    to_port = 22
}
```

**Comment by ddymko** [comment]
@scross01 

For something like SSH you do not need to define the `to_port`.  Since you are not ranging from port x to port y.

```
resource vultr_firewall_rule ssh {
    firewall_group_id = vultr_firewall_group.default.id
    protocol = "tcp"
    network = "0.0.0.0/0"
    from_port = 22
}
```

**Comment by scross01** [comment]
perfect, thanks its working now.

**Comment by OJFord** [comment]
@ddymko The error if `to_port` *is* specified, and is the same as `from_port` (and I guess it's the same if it's lower is very confusing:

> Error: Err creating firewall group : Unable to add rule: Invalid port number - must be between 1 and 65535

I didn't even realise it was for ranges, I assumed both had to be specified, and that it was for translating external/internal ports. So, thanks for the fix, but the error could be clearer! 🙂
