### ISSUE TITLE
[BUG] - `os_id` is required; `snapshot_id` is ignored

### ISSUE THREAD

**Issue by OJFord** [vultr/terraform-provider-vultr-community#95]
**Describe the bug**
If you specify a `snapshot_id` only, you get an error on a `vultr_server` resource that `os_id` is required.

If you then add `os_id = data.vultr_snapshot.mysnapshot.os_id`, the `apply` succeeds but the resulting server was not created from the snapshot, it's just the same OS as the snapshot's `os_id`, as if the `snapshot_id` wasn't specified at all.

**To Reproduce**
```hcl
resource "vultr_server" "test" {
  region_id         = "${data.vultr_region.test.id}"
  plan_id           = "${data.vultr_plan.test.id}"
  os_id             = "${data.vultr_snapshot.test.os_id}"  # error if not specified
  snapshot_id       = "${data.vultr_snapshot.test.id}"
  # ...
}
```

**Expected behavior**
`os_id` not required if `snapshot_id` is specified.

or at least, if it is required, `snapshot_id` is still used.

**Desktop (please complete the following information where applicable:**
```
Terraform v0.12.5
[...]
+ provider.vultr (unversioned)
```

**Additional context**

**Comment by ddymko** [comment]
@OJFord 

`os_id` is required for `snapshot`

This is due to the API design. The os_id is always required and there are special `osid` that correspond to specific types.

These are the following server options that require os_id and their corresponding value
- SnapshotID -> 164
- ScriptID -> 159 (or any os_id)
- ISOID -> 159
- APPID -> 186

So in the instance where your snapshot was not being used ... this is because the os_id that had to be passed in was `164` to inform the API that you want to create a server from a given snapshot_id. 

https://www.vultr.com/api/#server_create
```
ISOID string (optional) If you've selected the 'custom' operating system, this is the ID of a specific ISO to mount during the deployment.
SCRIPTID integer (optional) If you've not selected a 'custom' operating system, this can be the SCRIPTID of a startup script to execute on boot. See v1/startupscript/list.
SNAPSHOTID string (optional) If you've selected the 'snapshot' operating system, this should be the SNAPSHOTID (see v1/snapshot/list) to restore for the initial installation.
```

**Comment by OJFord** [comment]
@ddymko Ouch, I see, many thanks for the detailed explanation!

May I convert this into a feature request: `snapshot_id` implies `os_id = 164` (resp. the others)?

**Comment by ddymko** [comment]
@OJFord 

We actually had this implementation in place but unfortunately we had a lot of unexpected behavior with our API that caused us to remove it: https://github.com/vultr/terraform-provider-vultr/pull/91

This is definitely a pain point because of our API and we are working towards cleaning up our API and make it more robust (and remove headaches like this one)

**Comment by OJFord** [comment]
@ddymko Thanks again for your explanation, that did work.

However, there seems to be a related issue that after `terraform apply` with `os_id = 164` and a `snapshot_id`, a subsequent `terraform plan` shows:
```
     ~ os_id             = 244 -> 164
```

i.e. when it refreshes the resource from the API it gets the underlying `os_id = 244`, and thinks it needs to be changed to `164`.

Without above suggestion/#91, I think it could be fixed by checking `GET /v1/snapshot/list` for whether the refreshed `os_id` matches that underlying the `snapshot_id`.

**Comment by OJFord** [comment]
In fact, this is a show-stopper, because it means you can never `apply` again:

```
Error: Error occured while updating os_id for server <N> : Invalid operating system.
```

I'll create a separate issue.
