### ISSUE TITLE
remote-exec ssh host not populated

### ISSUE THREAD

**Issue by hadleyrich** [vultr/terraform-provider-vultr-community#98]
When adding a remote-exec to a config it's acutally executed on the localhost as the host field is not populated:

```
resource "vultr_server" "this" {
  label       = var.server_name
  plan_id     = "${data.vultr_plan.starter.id}"
  os_id       = "${data.vultr_os.ubuntu-1904.id}"
  region_id   = "${data.vultr_region.sydney.id}"
  ssh_key_ids = var.ssh_key_ids
  provisioner "remote-exec" {
    inline     = [
      "apt update",
      "apt -y dist-upgrade",
    ]
  }
}
```

Some output:

```
module.vultr_server_testypants2.vultr_server.this: Still creating... [1m30s elapsed]
module.vultr_server_testypants1.vultr_server.this: Still creating... [1m30s elapsed]
module.vultr_server_testypants2.vultr_server.this: Provisioning with 'remote-exec'...
module.vultr_server_testypants2.vultr_server.this (remote-exec): Connecting to remote host via SSH...
module.vultr_server_testypants2.vultr_server.this (remote-exec):   Host:
module.vultr_server_testypants2.vultr_server.this (remote-exec):   User: root
module.vultr_server_testypants2.vultr_server.this (remote-exec):   Password: false
module.vultr_server_testypants2.vultr_server.this (remote-exec):   Private key: false
module.vultr_server_testypants2.vultr_server.this (remote-exec):   Certificate: false
module.vultr_server_testypants2.vultr_server.this (remote-exec):   SSH Agent: true
module.vultr_server_testypants2.vultr_server.this (remote-exec):   Checking Host Key: false
module.vultr_server_testypants2.vultr_server.this (remote-exec): Connected!
module.vultr_server_testypants2.vultr_server.this (remote-exec): 
module.vultr_server_testypants2.vultr_server.this (remote-exec): 0% [Working]
```

The reason it shows connected there is because I can SSH to my localhost.

**Comment by OJFord** [comment]
I agree that it would be better if default `connection.host = self.main_ip` (since [Terraform docs say 'This is usually specified by the provider.'](https://www.terraform.io/docs/provisioners/connection.html#argument-reference)), but you can specify this yourself:

```hcl
resource "vultr_server" "this" {
  # ...
  connection {
    host = self.main_ip
    agent = true
  }
}
```

That an empty `host` connects to localhost if `sshd` running there is 'interesting' terraform core behaviour, IMO.

**Comment by ddymko** [comment]
@hadleyrich 

You will need to define a connection block within your `provisioner`


```
  provisioner "remote-exec" {
    inline     = [
      "apt update",
      "apt -y dist-upgrade",
    ]

    connection {
        type     = "ssh"
        host     = "${vultr_server.this.main_ip}"
        user     = "root"
        password = "${vultr_server.this.default_password}"

   }
  }
```

**Comment by hadleyrich** [comment]
Thanks for the replies guys. I guess not a bug then, I had assumed that the provider would specify it.

**Comment by OJFord** [comment]
@hadleyrich It should do/usually does, per core docs. I suppose it's not a *bug*, but IMO would be good to add to the provider @ddymko.

**Comment by hadleyrich** [comment]
@OJFord Agreed, I've not come across it before and it would be a nice to have. Perhaps a feature request or included in documentation, rather than a bug.

**Comment by ddymko** [comment]
@OJFord This isn't a bug since this is not a mandatory feature required by Terraform and there is a way to define your connection information. Also not all providers do this there are some cloud providers who do and some who don't. 

@OJFord @hadleyrich I created a new enhancement ticket #100 that addresses this topic. It will set the connection information for regular instances and baremetal. This will remove the headache of having to set the connection blocks.
